version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        secretKey: 1234567890
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=3000
    restart: always
    container_name: cw-indonesia-app
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/cw-indonesiaø
  postgres:
    image: postgres:9.6
    container_name: cw-indonesia-postgres
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cw_indonesia_platform
    volumes: 
      - db_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    container_name: cw-indonesia-redis
    ports:
      - "6379:6379"
volumes:
  db_data:
