apiVersion: v1
kind: Service
metadata:
  labels:
    name: indonesia-platform-staging
  name: indonesia-platform-staging
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: indonesia-platform-staging
